version: '3.9'

services:
  db:
    image: postgres:16
    container_name: dronebuilder-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DroneBuilderDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dronebuilder-net

volumes:
  postgres_data:

networks:
  dronebuilder-net:
